pipeline{
    agent any

    options {
        parallelsAlwaysFailFast()
    }

    parameters {
        string(name: "DEPLOY_PATH", defaultValue: "deploy", description : "path to deploy")
    }

    environment {
        REGION = "ap-northeast-2"
    }

    stages {

        stage ("Build Docker Image") {
            steps {
                sh "docker build -f ${DEPLOY_PATH}/Dockerfile.test -t node:test ."
            }
            
            post {
                success {
                    echo "Success CI Test"
                }

                failure {
                    echo "Fila CI Test"
                }
            }
        }

        stage("CI test") {
        
            steps {
                sh "docker images"
            }
        }
        

        // stage("Build Docker image") {
        //     steps {
        //         echo "Build Docker Image"
        //     }

        //     post {
        //         success {
        //             echo "Build Success"
        //         }

        //         failure {
        //             echo "Build Failure"
        //         }
        //     }
        // }
    }

    post {
        success{
            echo "success"
        }

        failure{
            echo "failure"
        }
    }
}